[0m15:18:52.604414 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A75A413F90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A75A1FC110>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A75A1FC190>]}


============================== 15:18:52.615429 | c3f34579-8ed4-4460-bebb-649b6eae0a29 ==============================
[0m15:18:52.615429 [info ] [MainThread]: Running with dbt=1.9.0-b2
[0m15:18:52.617382 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\Naim\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt init my-project', 'send_anonymous_usage_stats': 'True'}
[0m15:18:52.653283 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse dict {'dir': WindowsPath('C:/Users/Naim/.dbt')}
[0m15:18:52.654315 [info ] [MainThread]: Creating dbt configuration folder at 
[0m15:19:38.708568 [debug] [MainThread]: Starter project path: C:\Users\Naim\data_warehouse_for_ethiopian_medical\venv\Lib\site-packages\dbt\include\starter_project
[0m15:19:38.824127 [info ] [MainThread]: 
Your new dbt project "my_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m15:19:38.828083 [info ] [MainThread]: Setting up your profile.
[0m15:21:52.311248 [info ] [MainThread]: Profile my_project written to C:\Users\Naim\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m15:21:52.314868 [debug] [MainThread]: Command `dbt init` succeeded at 15:21:52.314350 after 179.82 seconds
[0m15:21:52.316150 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A7540D26D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A7540D2690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A7598FA9D0>]}
[0m15:21:52.316829 [debug] [MainThread]: Flushing usage events
[0m15:22:14.293637 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:26:01.053934 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000200C33235D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000200C33426D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000200C3343DD0>]}


============================== 15:26:01.063799 | 1b9a9602-fcaf-431f-9a77-7c030664e82c ==============================
[0m15:26:01.063799 [info ] [MainThread]: Running with dbt=1.9.0-b2
[0m15:26:01.066088 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Naim\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt run', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:26:01.067136 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Naim\data_warehouse_for_ethiopian_medical\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:26:01.072069 [debug] [MainThread]: Command `dbt run` failed at 15:26:01.072069 after 0.15 seconds
[0m15:26:01.073067 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000200C3348A50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000200C3323390>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000200C3343150>]}
[0m15:26:01.074481 [debug] [MainThread]: Flushing usage events
[0m15:26:07.315404 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:29:20.905591 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B776359310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B776383250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B776382F10>]}


============================== 15:29:20.909992 | 300e8d8f-f586-4e23-b772-7ef95dc91c86 ==============================
[0m15:29:20.909992 [info ] [MainThread]: Running with dbt=1.9.0-b2
[0m15:29:20.911241 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Naim\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'invocation_command': 'dbt run', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:29:20.912139 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Naim\data_warehouse_for_ethiopian_medical\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:29:20.914132 [debug] [MainThread]: Command `dbt run` failed at 15:29:20.914132 after 0.12 seconds
[0m15:29:20.915157 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B7763A2950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B7763A3CD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B77010E790>]}
[0m15:29:20.915157 [debug] [MainThread]: Flushing usage events
[0m15:29:23.043391 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m20:25:51.309539 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020F3E27A690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020F3B301510>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020F3E055050>]}


============================== 20:25:51.313721 | b57f1099-2ff0-4671-8257-ed309cbc17ab ==============================
[0m20:25:51.313721 [info ] [MainThread]: Running with dbt=1.9.0-b2
[0m20:25:51.314721 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Naim\\.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m20:25:51.315719 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Naim\data_warehouse_for_ethiopian_medical\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m20:25:51.317713 [debug] [MainThread]: Command `dbt run` failed at 20:25:51.317713 after 0.09 seconds
[0m20:25:51.318710 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020F3E268B90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020F3E268B10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020F3E290A10>]}
[0m20:25:51.319098 [debug] [MainThread]: Flushing usage events
[0m20:25:52.479820 [debug] [MainThread]: An error was encountered while trying to flush usage events
